spring.application.name=GATEWAY-SERVICE

server.port=8080

# Eureka Server
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true

# Gateway t? ??ng phát hi?n service t? Eureka
spring.cloud.gateway.discovery.locator.enabled=true
spring.cloud.gateway.discovery.locator.lower-case-service-id=true

# Logging
logging.level.org.springframework.cloud.gateway=DEBUG
logging.level.reactor.netty=INFO
spring.cloud.gateway.default-filters[0].name=AddResponseHeader
spring.cloud.gateway.default-filters[0].args.name=X-System-Name
spring.cloud.gateway.default-filters[0].args.value=Api-Gateway-System